# Generated by Django 5.2.2 on 2025-11-12 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('date_hired', models.DateField(default=django.utils.timezone.now)),
                ('work_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Off Day', 'Off Day')], default='Present', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('national_id_number', models.CharField(max_length=50, unique=True)),
                ('kra_pin', models.CharField(max_length=50, unique=True)),
                ('sha_number', models.CharField(help_text="Should start with 'SHA' followed by digits (e.g., SHA123456).", max_length=50, unique=True, verbose_name='SHA Number')),
                ('nssf_number', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_fired', models.DateField(blank=True, null=True)),
                ('fired_by', models.CharField(blank=True, max_length=100, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
