# Generated by Django 5.2.2 on 2026-01-06 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sha_number',
            field=models.CharField(help_text='Enter the government-issued SHA/SHIF number.', max_length=50, unique=True, verbose_name='SHA Number'),
        ),
    ]
