# Generated by Django 5.2.2 on 2026-01-08 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_date_hired_alter_employee_sha_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +2547XXXXXXXX or 07XXXXXXXX.', regex='^(\\+2547\\d{8}|07\\d{8})$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Bank account number must be 10–14 digits.', regex='^[0-9]{10,14}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be 11 characters: 1 letter, 9 digits, and 1 letter (e.g. A123456789B).', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')], verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NSSF number must be 7–10 digits.', regex='^[0-9]{7,10}$')], verbose_name='NSSF Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sha_number',
            field=models.CharField(help_text='Government-issued SHA/SHIF number.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SHA number must contain letters and numbers only.', regex='^[A-Za-z0-9]+$')], verbose_name='SHA Number'),
        ),
    ]
