# Generated by Django 5.2.2 on 2026-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
