# Generated by Django 5.2.2 on 2026-01-08 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_approved_at_employee_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_fired',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fired_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='termination_reason',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('O', 'Present'), ('X', 'Absent'), ('L', 'Leave'), ('S', 'Sick')], default='O', max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
