# Generated by Django 5.2.2 on 2026-01-08 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_date_fired_remove_employee_fired_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['job_number'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be 11 characters: 1 letter, 9 digits, and 1 letter.', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NSSF number must be 7–10 digits.', regex='^[0-9]{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sha_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SHA number must contain letters and numbers only.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be +2547XXXXXXXX or 07XXXXXXXX.', regex='^(\\+2547\\d{8}|07\\d{8})$')]),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
