# Generated by Django 5.2.2 on 2026-02-19 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='approval_status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be 11 characters: 1 letter, 9 digits, and 1 letter.', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NSSF number must be 7–10 digits.', regex='^[0-9]{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sha_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='SHA number must contain letters and numbers only.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
