# Generated by Django 5.2.2 on 2025-11-12 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('material', 'Material'), ('tool', 'Tool'), ('fuel', 'Fuel')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Partially_Returned', 'Partially Returned')], default='Pending', max_length=20)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('previous_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('current_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_traveled', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
