# Generated by Django 5.2.2 on 2025-11-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        ('item_issuance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_received', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.vehicle'),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='issue_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item_issuance.issuerecord'),
        ),
    ]
