# Generated by Django 5.2.2 on 2026-01-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle Fuel'), ('machine', 'Machine Fuel')], help_text="Required when issue_type is 'fuel'", max_length=20, null=True),
        ),
    ]
