# Generated by Django 5.2.2 on 2026-01-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0003_issuerecord_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle Fuel'), ('machine', 'Machine Fuel')], max_length=20, null=True),
        ),
    ]
