# Generated by Django 5.2.2 on 2026-01-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0004_alter_issuerecord_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerecord',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='distance_traveled',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='fuel_efficiency',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='fuel_litres',
        ),
        migrations.RemoveField(
            model_name='issuerecord',
            name='previous_mileage',
        ),
    ]
