# Generated by Django 5.2.2 on 2026-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0005_remove_issuerecord_current_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueitem',
            name='current_odometer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='distance_travelled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='previous_odometer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
