# Generated by Django 5.2.2 on 2026-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0006_issueitem_current_odometer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueitem',
            name='odometer_reading_valid',
            field=models.BooleanField(default=True),
        ),
    ]
