# Generated by Django 5.2.2 on 2026-02-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_issuance', '0007_issueitem_odometer_reading_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueitem',
            name='odometer_reading_valid',
        ),
    ]
