# Generated by Django 5.2.2 on 2026-01-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockQuantity', '0001_initial'),
        ('inventory', '0010_alter_item_reorder_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryStock',
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stocks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.item',),
        ),
    ]
