# Generated by Django 5.2.2 on 2026-01-23 07:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockManager',
            fields=[
            ],
            options={
                'verbose_name': 'Livestock Manager',
                'verbose_name_plural': 'Livestock Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('StoreManager', 'Store Manager'), ('ManagingDirector', 'Managing Director'), ('AccountsManager', 'Accounts Manager'), ('HumanResourceManager', 'Human Resource Manager'), ('LivestockManager', 'Livestock Manager')], help_text='Determines user permissions and visibility', max_length=30),
        ),
    ]
