# Generated by Django 5.2.2 on 2025-11-12 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('vehicle', 'Vehicle'), ('tool', 'Tool'), ('material', 'Material')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('quantity_to_add', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('requires_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], max_length=20)),
                ('returned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('issued_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.issueditem')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('returnable', models.BooleanField(default=True)),
                ('uses_fuel', models.BooleanField(default=False)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_using_this_fuel', to='inventory.fuel')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('previous_mileage', models.PositiveIntegerField(default=0)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('previous_issued_litres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='inventory.item')),
            ],
        ),
    ]
