# Generated by Django 5.2.2 on 2025-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='uses_fuel',
        ),
        migrations.AlterField(
            model_name='tool',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
    ]
