# Generated by Django 5.2.2 on 2025-11-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_tool_fuel_type_remove_tool_uses_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools_using_this_fuel', to='inventory.fuel'),
        ),
        migrations.AddField(
            model_name='tool',
            name='uses_fuel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='condition',
            field=models.CharField(max_length=50),
        ),
    ]
