# Generated by Django 5.2.2 on 2026-01-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='inventory.fuel'),
        ),
    ]
