# Generated by Django 5.2.2 on 2026-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vehicle_fuel_efficiency_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
