# Generated by Django 5.2.2 on 2026-01-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_issueditem_current_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueditem',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='previous_issued_litres',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='previous_mileage',
        ),
        migrations.AddField(
            model_name='issueditem',
            name='calculated_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fuel Efficiency (km/L)'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_issuances', to='inventory.vehicle'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='issueditem',
            index=models.Index(fields=['vehicle', 'issue_date'], name='inventory_i_vehicle_7b07dd_idx'),
        ),
        migrations.AddIndex(
            model_name='issueditem',
            index=models.Index(fields=['item', 'status'], name='inventory_i_item_id_ba2042_idx'),
        ),
    ]
