# Generated by Django 5.2.2 on 2026-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_issueditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returneditem',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged')], max_length=20),
        ),
    ]
