# Generated by Django 5.2.2 on 2026-01-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_returneditem_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueditem',
            name='calculated_efficiency',
        ),
        migrations.RemoveField(
            model_name='issueditem',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_efficiency',
        ),
    ]
