# Generated by Django 5.2.2 on 2026-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_issueditem_calculated_efficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
