# Generated by Django 5.2.2 on 2026-01-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorder_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
    ]
