# Generated by Django 5.2.2 on 2026-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_remove_purchaseorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
