# Generated by Django 5.2.2 on 2026-02-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='accounts_with_money',
            field=models.JSONField(blank=True, help_text='Accounts marked by Accounts Manager that have available funds.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_account',
            field=models.CharField(blank=True, choices=[('petty_cash', 'Petty Cash'), ('hay_money', 'Hay Money'), ('steers_money', 'Steers Money'), ('afes', 'AFEs'), ('donors_money', 'Donors Money')], help_text='Account approved by MD for payment.', max_length=50, null=True),
        ),
    ]
