# Generated by Django 5.2.2 on 2026-02-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_purchaseorder_accounts_with_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full total amount paid to the supplier.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
